version: '3.8'

services:
  # Miembro Service
  miembro-service:
    build: ./miembro-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - gimnasio-network

  # Entrenador Service
  entrenador-service:
    build: ./entrenador-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - gimnasio-network

  # Clase Service
  clase-service:
    build: ./clase-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ENTRENADOR_SERVICE_URL=http://entrenador-service:8082
    networks:
      - gimnasio-network
    depends_on:
      - entrenador-service

  # Equipo Service
  equipo-service:
    build: ./equipo-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - gimnasio-network

  # Gateway Service
  gateway-service:
    build: ./gateway-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MIEMBRO_SERVICE_URL=http://miembro-service:8081
      - ENTRENADOR_SERVICE_URL=http://entrenador-service:8082
      - CLASE_SERVICE_URL=http://clase-service:8083
      - EQUIPO_SERVICE_URL=http://equipo-service:8084
    networks:
      - gimnasio-network
    depends_on:
      - miembro-service
      - entrenador-service
      - clase-service
      - equipo-service

networks:
  gimnasio-network:
    driver: bridge
